package ua.ck.ostapiuk.ghostapiukrssreader.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * Entity mapped to table ENTRY.
 */
public class Entry implements Serializable {

    private Long id;
    private String title;
    @SerializedName("content")
    private String description;
    private String author;
    private String publishedDate;
    private String link;

    public Entry() {
    }

    public Entry(Long id) {
        this.id = id;
    }

    public Entry(Long id, String title, String description, String author, String publishedDate, String link) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.author = author;
        this.publishedDate = publishedDate;
        this.link = link;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublishedDate() {
        return publishedDate;
    }

    public void setPublishedDate(String publishedDate) {
        this.publishedDate = publishedDate;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

}
